export const FETCH_CATS_PENDING = 'FETCH_CATS_PENDING'
export const FETCH_CATS_SUCCESS = 'FETCH_CATS_SUCCESS'
export const FETCH_CATS_FAILED = 'FETCH_CATS_FAILED'
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';